version: '3.1'

services:
        flask:
                image: flask
                build: ./backend
                restart: always
                networks:
                        - back_net
                environment:
                        FLASK_APP: flask.py
                        FLASK_DEBUG: 1
                        FLASK_ENV: development
networks:
    back_net:
        external: true
